# -*- coding: utf-8 -*-
"""AliGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XbQznn6VPdYJ2EYupobZ_vM5vUjV-t0
"""
import cv2, asyncio 
import torch
import numpy as np
from ultralytics import YOLO
from torchvision.transforms import Compose

# ---------- YOLO ----------
yolo = YOLO("yolov8n.pt")

# ---------- MiDaS ----------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# بارگذاری MiDaS + transforms رسمی
midas = torch.hub.load("intel-isl/MiDaS", "MiDaS_small")
midas.eval()

midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
transform = midas_transforms.small_transform

async def yoloProcess(frame):
    results = yolo(frame, conf=0.3, verbose=False)[0]
    await asyncio.sleep(0)
    return results
    
async def midasProcess(frame):
    input_batch = transform(frame)
    with torch.no_grad():
        depth = midas(input_batch)
        depth = torch.nn.functional.interpolate(
            depth.unsqueeze(1),
            size=frame.shape[:2],
            mode="bicubic",
            align_corners=False
        ).squeeze()
    depth_map = depth.cpu().numpy()
    await asyncio.sleep(0)
    return depth_map

async def process_frame(frame):
        """
        پردازش یک فریم:
        - تشخیص اشیاء با YOLOv8
        - تخمین عمق با MiDaS
        - انتخاب نزدیک‌ترین شئ
        - رسم خطوط فاصله‌ها با رنگ‌های متنوع
        - تصمیم حرکت
        """
        frame = cv2.resize(frame, (640, 480))
        h, w, _ = frame.shape
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        results, depth_map = await asyncio.gather(
            yoloProcess(frame_rgb),
            midasProcess(frame_rgb)
        )
        # ---------------- نزدیک‌ترین مانع ----------------
        closest_box = None
        min_depth = float("inf")

        if results.boxes is not None:
            for box in results.boxes:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                cx, cy_bottom = (x1 + x2) // 2, y2  # پایین باکس
                d = depth_map[cy_bottom, cx]
                if d < min_depth:
                    min_depth = d
                    closest_box = (x1, y1, x2, y2)

        # ---------------- تصمیم حرکتی ----------------
        decision = "GO FORWARD"

        if closest_box:
            x1, y1, x2, y2 = closest_box
            cx = (x1 + x2) // 2
            cy_bottom = y2  # پایین باکس

            # 🔲 کادر اصلی - سبز روشن
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 100), 3)

            # 📐 خطوط فاصله از کناره‌ها با رنگ‌های متفاوت
            dist_left = x1
            dist_right = w - x2

            cv2.line(frame, (0, cy_bottom), (x1, cy_bottom), (0, 255, 0), 2)       # خط چپ - سبز
            cv2.line(frame, (x2, cy_bottom), (w, cy_bottom), (0, 165, 255), 2)     # خط راست - نارنجی

            # 🟢 خط از پایین تصویر → پایین شئ (فاصله ربات تا مانع)
            cam_x, cam_y = w // 2, h - 1
            cv2.line(frame, (cam_x, cam_y), (cx, cy_bottom), (255, 0, 0), 2)  # آبی

            # 📏 نمایش عمق روی خط
            mid_x, mid_y = (cam_x + cx) // 2, (cam_y + cy_bottom) // 2
            cv2.putText(frame, f"Depth: {min_depth:.2f}", (mid_x, mid_y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,0,255), 2)  # بنفش

            # 🧮 نمایش طول خطوط کناری
            cv2.putText(frame, f"L: {dist_left}px", (10, cy_bottom - 15),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)
            cv2.putText(frame, f"R: {dist_right}px", (w - 150, cy_bottom - 15),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,165,255), 2)

            # 🤖 تصمیم حرکتی
            if cx < w * 0.4:
                decision = "TURN RIGHT"
            elif cx > w * 0.6:
                decision = "TURN LEFT"
            else:
                decision = "STOP / SLOW"

        # 🟡 تصمیم کل تصویر
        cv2.putText(frame, f"Decision: {decision}", (30, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 3)

        return frame, decision


# async def main():
#     img = cv2.imread("sample.jpg")
#     print(img.shape)
#     import matplotlib.pyplot as plt

#     frame, decision = await process_frame(img)
#     plt.imshow(frame)
#     plt.axis('off')
#     plt.show()

# if __name__ == "__main__":
#     asyncio.run(main())